### ISSUE TITLE
Wallbox Offline

### ISSUE THREAD

**Issue by Effihoff** [rkokkelk/nl.xseth.wallbox#37] opened 2024-09-15 07:17 UTC
Hi,
My wallbox goes very frequently offline in my Homey Pro, I've tried to uninstall and install it again but it doesn't help.
Any tips on how to solve it?
// Fredrik
![Screenshot_20240915_091434_Homey](https://github.com/user-attachments/assets/1332166b-1804-4823-8769-dd00254f3393)

**Comment by rkokkelk** [comment] 2024-11-25 20:48
Duplicate of #31 .

**Closed by rkokkelk** 2024-11-25 20:48 UTC
